version: '3'
services:
  app:
    container_name: express-api-boilerplate
    image: fpdrozd/express-api-boilerplate
    restart: always
    build: .
    environment:
      - NODE_ENV=production
    env_file:
      - app-config.env
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongodb:/data/db
    ports:
      - '27017:27017'
